import "./globals.css";
import type { Metadata } from "next";
import { Roboto, Rhodium_Libre } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "700"],
});

export const metadata: Metadata = {
  title: "Matheus Nascimento | My Bio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
